image: node:latest

stages:
  - start
  - deploy
  - finish
  
start:
  stage: start
  script:
    - pm2 stop imt
    
deploy:
  stage: deploy
  script:
    - cd ~ && cd /home/emissions/bots/idle_miner_tycoon && sudo git pull origin master

finish:
  stage: finish
  script:
    - pm2 start imt