image: node:latest

stages:
  - start
  - deploy
  - finish
  
start:
  stage: start
  script:
    - sudo pm2 stop imt
    - sudo pm2 del imt
    
deploy:
  stage: deploy
  script:
    - sudo git pull origin master
    - sudo npm update

finish:
  stage: finish
  script:
    - sudo pm2 start index.js --name "imt"