image: node:latest

stages:
  - start
  - deploy
  - finish
  
start:
  stage: start
  script:
    - sudo pm2 stop imt
    - sudo pm2 del imt
    
deploy:
  stage: deploy
  script:
    - cd /home/emissions/bots/idle_miner_tycoon && sudo git pull origin master && npm update

finish:
  stage: finish
  script:
    - cd /home/emissions/bots/idle_miner_tycoon && sudo pm2 start index.js --name "imt"